# Generated by Django 3.2.5 on 2021-07-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_boardcontent_author'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='board.boardcontent'),
            preserve_default=False,
        ),
    ]
