# Generated by Django 3.2.5 on 2021-07-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('test', models.CharField(max_length=10)),
            ],
        ),
    ]
