# Generated by Django 3.2.5 on 2021-07-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcontent',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
