# Generated by Django 3.2.5 on 2021-07-11 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_boardcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcontent',
            name='board_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_content', to='board.boardlist'),
        ),
    ]
